---
version: "3.9"
services:
  homer:
      image: b4bz/homer:22.02.1 # Have to use this version in order to work fine
      container_name: homer
      volumes:
        - /home/nhat/Homer-Modified/default-data:/www/assets
      ports:
        - 8092:8080
      #environment:
      #  - UID=1000
      #  - GID=1000
      restart: unless-stopped