---
- hosts: all
  vars:
    ansible_host_key_checking: false ##If you get an error about hosts not trusted
  become: yes
  become_user: root

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes

# ---
# - hosts: all
#   vars:
#     ansible_host_key_checking: false ##If you get an error about hosts not trusted
#   become: true
#   become_user: root
#   tasks:
#     - name: Update apt repo and cache on all Debian/Ubuntu boxes
#       apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

#     - name: Upgrade all packages on servers
#       apt: upgrade=dist force_apt_get=yes
